version: 2
updates:
- package-ecosystem: nuget
  directory: "/src"
  schedule:
    interval: daily
    time: "06:00"
    timezone: Europe/Moscow
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Sentry.AspNetCore
    versions:
    - 3.0.0
    - 3.0.1
    - 3.0.2
    - 3.0.3
    - 3.0.4
    - 3.0.5
    - 3.0.6
    - 3.0.7
    - 3.0.8
    - 3.1.0
    - 3.2.0
    - 3.3.0
    - 3.3.1
    - 3.3.2
    - 3.3.3
    - 3.3.4
  - dependency-name: Sentry
    versions:
    - 3.0.0
    - 3.0.1
    - 3.0.2
    - 3.0.3
    - 3.0.4
    - 3.0.5
    - 3.0.6
    - 3.0.7
    - 3.0.8
    - 3.1.0
    - 3.2.0
    - 3.3.0
    - 3.3.1
    - 3.3.2
    - 3.3.3
    - 3.3.4
  - dependency-name: Npgsql.EntityFrameworkCore.PostgreSQL
    versions:
    - 5.0.5
  - dependency-name: EPPlus
    versions:
    - 5.5.3
    - 5.5.4
    - 5.5.5
    - 5.6.0
    - 5.6.1
    - 5.6.2
    - 5.6.3
  - dependency-name: HangFire.Core
    versions:
    - 1.7.20
    - 1.7.21
    - 1.7.22
  - dependency-name: Hangfire.AspNetCore
    versions:
    - 1.7.20
    - 1.7.21
    - 1.7.22
  - dependency-name: OpenIddict.AspNetCore
    versions:
    - 3.0.1
    - 3.0.2
    - 3.0.3
  - dependency-name: OpenIddict.EntityFrameworkCore
    versions:
    - 3.0.1
    - 3.0.2
    - 3.0.3
  - dependency-name: Hangfire.PostgreSql
    versions:
    - 1.8.2
    - 1.8.3
    - 1.8.4
  - dependency-name: Microsoft.AspNetCore.Authentication.MicrosoftAccount
    versions:
    - 5.0.3
    - 5.0.4
    - 5.0.5
  - dependency-name: Microsoft.AspNetCore.Authentication.Google
    versions:
    - 5.0.3
    - 5.0.4
    - 5.0.5
  - dependency-name: Microsoft.AspNetCore.Mvc.NewtonsoftJson
    versions:
    - 5.0.3
    - 5.0.4
    - 5.0.5
  - dependency-name: Microsoft.AspNetCore.Authentication.Facebook
    versions:
    - 5.0.3
    - 5.0.4
    - 5.0.5
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.9.4
  - dependency-name: linq2db.Identity
    versions:
    - 3.3.0
  - dependency-name: linq2db
    versions:
    - 3.3.0
  - dependency-name: Npgsql
    versions:
    - 5.0.4
  - dependency-name: IdentityModel
    versions:
    - 5.0.1
    - 5.1.0
  - dependency-name: Markdig
    versions:
    - 0.24.0
  - dependency-name: MailKit
    versions:
    - 2.11.1
  - dependency-name: MSTest.TestAdapter
    versions:
    - 2.2.1
    - 2.2.2
    - 2.2.3
  - dependency-name: MSTest.TestFramework
    versions:
    - 2.2.1
    - 2.2.2
    - 2.2.3
  - dependency-name: Serilog.AspNetCore
    versions:
    - 4.0.0
- package-ecosystem: npm
  directory: "/src/ui"
  schedule:
    interval: daily
    time: "06:00"
    timezone: Europe/Moscow
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: react-i18next
    versions:
    - 11.8.10
    - 11.8.11
    - 11.8.12
    - 11.8.13
    - 11.8.14
    - 11.8.8
  - dependency-name: webpack
    versions:
    - 5.20.0
    - 5.20.1
    - 5.20.2
    - 5.21.0
    - 5.21.2
    - 5.22.0
    - 5.23.0
    - 5.24.0
    - 5.24.1
    - 5.24.2
    - 5.24.3
    - 5.24.4
    - 5.25.0
    - 5.25.1
    - 5.26.0
    - 5.26.2
    - 5.26.3
    - 5.27.0
    - 5.27.1
    - 5.27.2
    - 5.28.0
    - 5.30.0
    - 5.31.0
    - 5.31.1
    - 5.31.2
    - 5.32.0
    - 5.33.2
    - 5.34.0
    - 5.35.0
    - 5.35.1
    - 5.36.0
  - dependency-name: fork-ts-checker-webpack-plugin
    versions:
    - 6.1.1
    - 6.2.0
    - 6.2.1
    - 6.2.2
    - 6.2.3
    - 6.2.4
    - 6.2.5
  - dependency-name: eslint
    versions:
    - 7.23.0
    - 7.24.0
    - 7.25.0
  - dependency-name: antd
    versions:
    - 4.13.0
    - 4.14.1
    - 4.15.0
    - 4.15.1
    - 4.15.2
  - dependency-name: "@babel/core"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.1
    - 7.13.13
    - 7.13.14
    - 7.13.15
    - 7.13.16
    - 7.13.8
  - dependency-name: webpack-bundle-analyzer
    versions:
    - 4.4.1
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
    - 4.22.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
    - 4.22.0
  - dependency-name: css-loader
    versions:
    - 5.0.1
    - 5.0.2
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.1.4
    - 5.2.0
    - 5.2.1
  - dependency-name: less-loader
    versions:
    - 8.1.0
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.10
    - 7.13.12
    - 7.13.15
    - 7.13.5
    - 7.13.8
    - 7.13.9
  - dependency-name: "@babel/plugin-transform-runtime"
    versions:
    - 7.12.13
    - 7.12.15
    - 7.12.17
    - 7.13.0
    - 7.13.1
    - 7.13.10
    - 7.13.15
    - 7.13.2
    - 7.13.4
    - 7.13.5
    - 7.13.6
    - 7.13.7
    - 7.13.8
    - 7.13.9
  - dependency-name: webpack-cli
    versions:
    - 4.6.0
  - dependency-name: "@babel/preset-react"
    versions:
    - 7.12.13
    - 7.13.13
  - dependency-name: "@types/react-router"
    versions:
    - 5.1.12
    - 5.1.13
  - dependency-name: i18next
    versions:
    - 19.8.6
    - 19.9.0
    - 19.9.1
    - 19.9.2
    - 20.0.0
    - 20.1.0
    - 20.2.0
    - 20.2.1
  - dependency-name: "@types/react-dom"
    versions:
    - 17.0.3
  - dependency-name: react-dom
    versions:
    - 17.0.2
  - dependency-name: react
    versions:
    - 17.0.2
  - dependency-name: copy-webpack-plugin
    versions:
    - 8.0.0
    - 8.1.0
    - 8.1.1
  - dependency-name: "@babel/plugin-proposal-optional-chaining"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.12
    - 7.13.8
  - dependency-name: i18next-browser-languagedetector
    versions:
    - 6.1.0
  - dependency-name: "@types/react"
    versions:
    - 17.0.3
  - dependency-name: typescript
    versions:
    - 4.2.2
    - 4.2.3
    - 4.2.4
  - dependency-name: "@babel/plugin-proposal-nullish-coalescing-operator"
    versions:
    - 7.12.13
    - 7.13.0
    - 7.13.8
  - dependency-name: "@babel/preset-typescript"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
  - dependency-name: "@babel/plugin-proposal-class-properties"
    versions:
    - 7.12.13
    - 7.13.0
  - dependency-name: oidc-client
    versions:
    - 1.11.0
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: "06:00"
    timezone: Europe/Moscow
  open-pull-requests-limit: 10
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
    time: "06:00"
    timezone: Europe/Moscow
  open-pull-requests-limit: 10
