ALTER DEFAULT PRIVILEGES IN SCHEMA hangfire GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO web;
GRANT USAGE ON SCHEMA hangfire TO web;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA hangfire TO web;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA hangfire TO web;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA hangfire TO web;